services:
  pytorch-cuda:
    image: pytorch-cuda:latest
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    command: ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--allow-root"]
    ports:
      - "8888:8888"
